#! /bin/sh

picom &
redshift &
dunst &
feh --bg-scale /home/nixos-dotfiles/assets/wallpaper.PNG

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config focus_follows_pointer true
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a mpv state=floating